//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LittleBiologist {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LBio_Res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LBio_Res() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LittleBiologist.LBio_Res", typeof(LBio_Res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 // Upgrade NOTE: replaced &apos;mul(UNITY_MATRIX_MVP,*)&apos; with &apos;UnityObjectToClipPos(*)&apos;
        ///
        ///// Upgrade NOTE: replaced &apos;mul(UNITY_MATRIX_MVP,*)&apos; with &apos;UnityObjectToClipPos(*)&apos;
        ///
        ///Shader &quot;Futile/HoloGridMod&quot; 
        ///{
        ///	Properties 
        ///	{
        ///		_MainTex (&quot;Base (RGB) Trans (A)&quot;, 2D) = &quot;white&quot; {}
        ///		_Color(&quot;GridColor&quot;,Color) = (0.32, 0.38, 0.66, 1)
        ///	}
        ///	
        ///	Category 
        ///	{
        ///		Tags {&quot;Queue&quot;=&quot;Transparent&quot; &quot;IgnoreProjector&quot;=&quot;True&quot; &quot;RenderType&quot;=&quot;Transparent&quot;}
        ///		ZWrite Off
        ///		//Alphatest Greater 0
        ///		Blend SrcAlpha OneMinusSrcAlpha 
        ///		Fog { Color(0,0, [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string CompiledShader {
            get {
                return ResourceManager.GetString("CompiledShader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 // Compiled shader for PC, Mac &amp; Linux Standalone, uncompressed size: 5.5KB\r\n\r\nShader \&quot;Test\&quot; {\r\nSubShader { \r\n\r\n\r\n // Stats for Vertex shader:\r\n //       d3d11 : 5 math\r\n //    d3d11_9x : 5 math\r\n //        d3d9 : 5 math\r\n //      opengl : 5 math\r\n // Stats for Fragment shader:\r\n //        d3d9 : 3 math\r\n //      opengl : 1 math\r\n Pass {\r\nProgram \&quot;vp\&quot; {\r\nSubProgram \&quot;opengl \&quot; {\r\n// Stats: 5 math\r\nBind \&quot;vertex\&quot; Vertex\r\nBind \&quot;normal\&quot; Normal\r\n\&quot;!!ARBvp1.0\r\nPAR [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string YellowShader {
            get {
                return ResourceManager.GetString("YellowShader", resourceCulture);
            }
        }
    }
}
