//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LittleBiologist {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LBio_Res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LBio_Res() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LittleBiologist.LBio_Res", typeof(LBio_Res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 // Compiled shader for PC, Mac &amp; Linux Standalone, uncompressed size: 18.9KB
        ///
        ///Shader &quot;Futile/HoloGrid&quot; {
        ///Properties {
        /// _MainTex (&quot;Base (RGB) Trans (A)&quot;, 2D) = &quot;white&quot; {}
        /// _Color (&quot;GridColor&quot;, Color) = (0.32,0.38,0.66,1)
        ///}
        ///SubShader { 
        /// Tags { &quot;QUEUE&quot;=&quot;Transparent&quot; &quot;IGNOREPROJECTOR&quot;=&quot;true&quot; &quot;RenderType&quot;=&quot;Transparent&quot; }
        ///
        ///
        /// // Stats for Vertex shader:
        /// //       d3d11 : 9 math
        /// //        d3d9 : 10 math
        /// //      opengl : 10 math
        /// // Stats for Fragment shader:
        /// //       d3d11 : 157 math, 13 texture [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string CompiledShader {
            get {
                return ResourceManager.GetString("CompiledShader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 // Compiled shader for PC, Mac &amp; Linux Standalone, uncompressed size: 12.2KB
        ///
        ///Shader &quot;Custom/GaussianBlur&quot; {
        ///Properties {
        /// _MainTex (&quot;Base (RGB) Trans (A)&quot;, 2D) = &quot;white&quot; {}
        /// _Col (&quot;TempCol&quot;, Color) = (0,0,0,1)
        ///}
        ///SubShader { 
        /// Tags { &quot;QUEUE&quot;=&quot;Transparent&quot; &quot;IGNOREPROJECTOR&quot;=&quot;true&quot; &quot;RenderType&quot;=&quot;Transparent&quot; }
        /// GrabPass {
        /// }
        ///
        ///
        /// // Stats for Vertex shader:
        /// //       d3d11 : 9 math
        /// //        d3d9 : 10 math
        /// //      opengl : 10 math
        /// // Stats for Fragment shader:
        /// //       d3d11 : 36 math, 12  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string CustomBlur {
            get {
                return ResourceManager.GetString("CustomBlur", resourceCulture);
            }
        }
    }
}
